# Generated by Django 6.0.1 on 2026-02-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_id',
            field=models.CharField(default='default_checkout_OLD', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='role',
            field=models.CharField(choices=[('taxi', 'Taxi'), ('client', 'Client'), ('coiffeuse', 'Coiffeuse')], max_length=20),
        ),
    ]
