# Generated by Django 6.0.1 on 2026-02-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment_checkout_id_payment_checkout_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
