# Generated by Django 6.0.1 on 2026-02-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_payment_checkout_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='checkout_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
