# Generated by Django 6.0.1 on 2026-02-26 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_depart', models.CharField(max_length=255)),
                ('adresse_arrivee', models.CharField(max_length=255)),
                ('prix_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('temps_arrivee', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('proposed', 'Proposition taxi'), ('accepted', 'Acceptée'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.client')),
                ('taxi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.taxi')),
            ],
        ),
    ]
