# Generated by Django 6.0.1 on 2026-03-02 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_payment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_propose', models.DecimalField(decimal_places=2, max_digits=8)),
                ('temps_arrivee', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='core.course')),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.taxi')),
            ],
        ),
    ]
