# Generated by Django 6.0.1 on 2026-03-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_proposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='arrivee_estimee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
