# Generated by Django 6.0.1 on 2026-03-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_course_arrivee_estimee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='paiement_admin',
            field=models.BooleanField(default=False),
        ),
    ]
