# Generated by Django 6.0.1 on 2026-03-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_coiffeuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='coiffeuse',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coiffeuse',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
