# Generated by Django 6.0.1 on 2026-03-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_coiffeuse_services_coiffeuse_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coiffeuse',
            name='services',
            field=models.CharField(blank=True, choices=[('coiffure', 'Coiffure'), ('manicure_pedicure', 'Manicure & Pédicure'), ('pose_cils', 'Pose cils'), ('maquillage', 'Maquillage')], max_length=50, null=True),
        ),
    ]
