# Generated by Django 6.0.1 on 2026-03-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_coiffeuse_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coiffeuse',
            name='services',
            field=models.CharField(blank=True, help_text='Selectionnez un ou plusieurs services proposés par la coiffeuse (ex: coiffure, manicure_pedicure, pose_cils, maquillage)', max_length=255, null=True),
        ),
    ]
