# Generated by Django 6.0.1 on 2026-03-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_coiffeuse_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='coiffeuse',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Indique si la coiffeuse est disponible pour des propositions'),
        ),
    ]
