# Generated by Django 6.0.1 on 2026-03-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_coiffeuse_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='coiffeuse',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coiffeuse',
            name='wants_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coiffeuse',
            name='website_or_tiktok_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
