# Generated by Django 6.0.1 on 2026-03-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_coiffeuse_instagram_link_coiffeuse_wants_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coiffeuse',
            name='ville',
            field=models.CharField(blank=True, choices=[('bruxelles', 'Bruxelles'), ('anvers', 'Anvers'), ('gand', 'Gand'), ('charleroi', 'Charleroi'), ('liege', 'Liège'), ('namur', 'Namur'), ('mons', 'Mons'), ('bruge', 'Bruges'), ('louvain', 'Louvain'), ('malines', 'Malines'), ('aalst', 'Alost'), ('hasselt', 'Hasselt'), ('kortrijk', 'Courtrai'), ('ostende', 'Ostende'), ('la_louviere', 'La Louvière')], max_length=50, null=True),
        ),
    ]
